### ISSUE TITLE
The YouTube video is restricted

### ISSUE THREAD

**Issue by DiloromA** [learn-co-curriculum/hash-overview-readme#27]
The Youtube video did not play first, because my YouTube account was on restricted mode. I had to changed the mode to off, then play it.

**Comment by drakeltheryuujin** [comment]
Hi @Dillorom,

Raising issues on GitHub should be reserved for problems with the Learn.co curriculum.

This sounds like an issue with youtube user settings, which we do not have the capacity to support. If you still feel that this is an issue with the curriculum, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
