### ISSUE TITLE
Link to RubyMonk Hashes in the Resources section is broken

### ISSUE THREAD

**Issue by SwellPF** [learn-co-curriculum/hash-overview-readme#29]
The link to RubyMonk Hashes (URL: http://rubymonk.com/learning/books/1-ruby-primer/chapters/10-hashes-in-ruby/lessons/46-introduction-to-ruby-hashes) in the "Introduction to Hashes" readme returns a 502 Bad Gateway error.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @SwellPF.

We have updated the materials, replaced this link and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
